version: '3.1'
services :
  db:
    image: postgres:14-bullseye
    container_name: db
    ports:
      - 5432:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./.pg-data:/var/lib/postgresql/data
  admin:
    image: adminer
    container_name: admin
    restart: unless-stopped
    depends_on: 
      - db
    ports:
      - 8080:8080
